adobe/aio-lib-java

- events_ingress/src/main/java/com/adobe/event/publish/PublishService.java
- events_ingress/src/main/java/com/adobe/event/publish/PublishServiceImpl.java
- events_ingress/src/main/java/com/adobe/event/publish/api/PublishApi.java
- events_ingress/src/test/java/com/adobe/event/publish/PublishServiceTestDrive.java
https://github.com/adobe/aio-lib-java/issues/22
mapping the upcoming new publish API endpoint allow raw event payload  (non CloudEvents) to be published
> GH-22 `events-ingress` map the new `Adobe I/O Events` Raw Events publication endpoint 

- events_mgmt/src/main/java/com/adobe/event/management/model/RegistrationInputModel.java
Need this for someone who wants to register multiple combinations of Provider ID and Event Code to one Journal/Webhook.
https://github.com/adobe/aio-lib-java/issues/24
Need this for someone who wants to register multiple combinations of Provider ID and Event Code to one Journal/Webhook.
> Issue 24 - Method to add multiple EventsOfInterest to the model

- core/src/main/java/com/adobe/util/Constants.java
- events_mgmt/src/main/java/com/adobe/event/management/ConflictErrorDecoder.java
- events_mgmt/src/main/java/com/adobe/event/management/ConflictException.java
- events_mgmt/src/main/java/com/adobe/event/management/ProviderService.java
- events_mgmt/src/main/java/com/adobe/event/management/ProviderServiceImpl.java
- events_mgmt/src/main/java/com/adobe/event/management/model/ErrorResponse.java
- events_mgmt/src/main/java/com/adobe/event/management/model/ProviderInputModel.java
- events_mgmt/src/test/java/com/adobe/event/management/ProviderServiceUpdateTestDrive.java
#30 adding a `createOrUpdateProvider()` method to the ProviderService
> GH-30 adding a `createOrUpdateProvider()` method to the ProviderService

- events_xdm/README.md
- events_xdm/pom.xml
- events_xdm/src/main/java/com/adobe/xdm/event/AemPageModificationEvent.java
- events_xdm/src/main/java/com/adobe/xdm/extensions/aem/PageModification.java
- osgi/pom.xml
- pom.xml
https://github.com/adobe/aio-lib-java/issues/37
> GH-37 adding `aio-lib-java-events-xdm` module: the  Adobe I/O Events Extensions models.

- pom.xml
maven release plugin was complaining
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project aio-lib-java: Execution default-cli of goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare: java.lang.NoSuchMethodError: org.apache.maven.shared.invoker.InvocationRequest.setInteractive(Z)Lorg/apache/maven/shared/invoker/InvocationRequest;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-release-plugin:2.5.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = …
> Fix workflow

- .github/workflows/sitedocs.yaml
- core/src/main/java/com/adobe/aio/feign/AIOHeaderInterceptor.java
- core/src/main/java/com/adobe/aio/util/Constants.java
- events_ingress/src/main/java/com/adobe/aio/event/publish/feign/FeignPublishService.java
- events_journal/src/main/java/com/adobe/aio/event/journal/feign/FeignJournalService.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/FeignProviderService.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/FeignRegistrationService.java
- ims/src/main/java/com/adobe/aio/ims/feign/JWTAuthInterceptor.java
- ims/src/test/java/com/adobe/aio/ims/feign/FeignImsServiceTestDrive.java
Extract API Key header to separate AIO Request Interceptor.
So that can add the `x-gw-ims-org-id` header to requests .
> Updates to Feign Header Processing

- events_mgmt/src/main/java/com/adobe/aio/event/management/model/ProviderInputModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/Registration.java
- pom.xml
* removing the deprecated Registration Type
* allowing the ProviderInputModel.providerMetadataId to be optional and defaulted to 3rd party Custom Events
> GH-110 removing the deprecated Registration Type

- events_mgmt/src/main/java/com/adobe/aio/event/management/model/Provider.java
see https://github.com/adobe/aio-lib-java/issues/112
Adobe I/O Events Management API now expose an (optional) Provider instance_id
with this PR we now map it.
> GH-112 adding the Provider model's instanceId

- aem/events_mgmt_aem/src/main/java/com/adobe/aio/aem/event/management/internal/EventProviderConfigSupplierImpl.java
- aem/events_mgmt_aem/src/main/java/com/adobe/aio/aem/event/management/ocd/EventProviderConfig.java
- events_journal/src/test/java/com/adobe/aio/event/management/feign/FeignProviderServiceIntegrationTest.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/Provider.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/ProviderInputModel.java
- ims/src/main/java/com/adobe/aio/util/WorkspaceUtil.java
see https://github.com/adobe/aio-lib-java/issues/102
* mapping the new Provider Registration input model allowing to specify the `event_delivery_format`
* adding `event_delivery_format` in the AEM OSGI Provider configurations
* default being now `cloud_events_v1` instead of the old legacy `adobe_io` format
replacing https://github.com/adobe/aio-lib-java/pull/119 to have the secrets available for integration tests to run
> GH-102 mapping the new Provider Registration input model allowing to specify the `event_delivery_format`

- aem/core_aem/pom.xml
- aem/events_ingress_aem/pom.xml
- aem/events_mgmt_aem/pom.xml
- aem/events_osgi_mapping/pom.xml
- aem/lib_osgi/src/main/bnd/aio-lib-osgi.bnd
- aem/pom.xml
- pom.xml
fixing `aio-lib-osgi` : it now exports `io.openapitools.jackson.dataformat.hal.*` packages
* GH-142
> GH-142 fixing `aio-lib-osgi` : it now exports `io.openapitools.jackson.dataformat.hal.*` packages

- core/src/main/java/com/adobe/aio/workspace/Workspace.java
- events_ingress/src/test/java/com/adobe/aio/event/publish/feign/FeignPublishServiceTestDrive.java
- events_journal/src/test/java/com/adobe/aio/event/journal/feign/FeignJournalServiceTestDrive.java
- events_mgmt/src/test/java/com/adobe/aio/event/management/feign/FeignProviderServiceTestDrive.java
- events_mgmt/src/test/java/com/adobe/aio/event/management/feign/FeignRegistrationServiceTestDrive.java
- events_test/src/main/java/com/adobe/aio/event/journal/JournalServiceTester.java
- events_test/src/main/java/com/adobe/aio/event/management/ProviderServiceTester.java
- events_test/src/main/java/com/adobe/aio/event/management/RegistrationServiceTester.java
- events_test/src/main/java/com/adobe/aio/event/publish/PublishServiceTester.java
- events_test/src/test/java/com/adobe/aio/event/journal/JournalServiceIntegrationTest.java
- events_test/src/test/java/com/adobe/aio/event/management/ProviderServiceIntegrationTest.java
- ims/src/main/java/com/adobe/aio/util/WorkspaceUtil.java
- ims/src/test/java/com/adobe/aio/ims/feign/FeignImsServiceIntegrationTest.java
- ims/src/test/java/com/adobe/aio/ims/feign/FeignImsServiceTestDrive.java
* re-introducing `Workspace.getCredentialId()`
* moving back `WorkspaceUtil` to  `com.adobe.aio.util`
> Some proposal for better Backward compatibility

- core/src/main/java/com/adobe/aio/util/JacksonUtil.java
- pom.xml
Let's stick to the old CloudEvents v1 spec and package for now
as we did not test the latest package and as this format is key to our partners integration
> Let's stick to the old CloudEvents v1 spec and package for now

- pom.xml
As it looks like 3.1.1 has a similar bug to https://issues.apache.org/jira/browse/MINSTALL-151 that prevents our `aem65` profile to run
see https://github.com/adobe/aio-lib-java/issues/170
> GH-170 downgrading `maven-install-plugin` to `2.5.2`

- events_test/src/main/java/com/adobe/aio/event/management/RegistrationServiceTester.java
[GH-188](https://github.com/adobe/aio-lib-java/issues/188) a fix for runtime registration create assertion failure on webhook url.
Helps assert successfully for the created runtime webhook registration
Using runtime e2e test via `aio_events_itests`
> fixing the runtime registration create assertion

- aem/lib_osgi/pom.xml
- ims/pom.xml
- ims/src/main/java/com/adobe/aio/ims/util/KeyStoreUtil.java
- pom.xml
The Jakarta Bind API has been deprecated. The only use in this library is for Binary handling, which is part of Java8 API.
Jakarta dependency causes collisions with downstream libraries.
see https://github.com/adobe/aio-lib-java/issues/193
> Remove all references to deprecated Jakarta libraries

- events_webhook/src/main/java/com/adobe/aio/event/webhook/service/EventVerifier.java
- events_webhook/src/test/java/com/adobe/aio/event/webhook/service/EventVerifierTest.java
Adds support to handle bach event payloads during event verification for recipient check.
https://github.com/adobe/aio-lib-java/issues/194
To enable webhook batch e2e to succeed during event verification
Will be verified by the batch e2e.
> feat: support for handling batch payload during event verification

- events_mgmt/src/main/java/com/adobe/aio/event/management/RegistrationService.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/ConflictException.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/FeignProviderService.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/FeignRegistrationService.java
- events_test/src/main/java/com/adobe/aio/event/management/RegistrationServiceTester.java
- events_test/src/test/java/com/adobe/aio/event/journal/JournalServiceIntegrationTest.java
- events_test/src/test/java/com/adobe/aio/event/management/ProviderServiceIntegrationTest.java
- events_test/src/test/java/com/adobe/aio/event/management/RegistrationServiceIntegrationTest.java
- events_test/src/test/java/com/adobe/aio/event/publish/PublishServiceIntegrationTest.java
See [issue](https://github.com/adobe/aio-lib-java/issues/199) description
https://github.com/adobe/aio-lib-java/issues/199
https://jira.corp.adobe.com/browse/CI-6365
Make our e2e more resilient
Using `aio-events-itests` running locally
> refactoring registration service to make it resilient for conflict errors

- events_test/src/main/java/com/adobe/aio/event/management/ProviderServiceTester.java
- events_test/src/main/java/com/adobe/aio/event/management/RegistrationServiceTester.java
Related Issue
https://github.com/adobe/aio-lib-java/issues/199
https://jira.corp.adobe.com/browse/CI-6365
> better logging, removing updateRuntimeRegistration api after leveraging createOrUpdate

- aem/lib_osgi/src/main/bnd/aio-lib-osgi.bnd
Recently we upgraded to 1.1.12 version of the sdk and started using com.adobe.aio.auth but we were not able to start our bundle on AEM since the artifact aio-lib-osgi is not exporting this package.
Added this package in the export list so that the dependent bundles can access the classes of this package.
> added export instruction for auth package

- aem/lib_osgi/src/main/bnd/aio-lib-osgi.bnd
Recently we upgraded to 1.1.12 version of the sdk and started using com.adobe.aio.auth but we were not able to start our bundle on AEM since the artifact aio-lib-osgi is not exporting this package. Added this package in the export list so that the dependent bundles can access the classes of this package.
* GH-186
* https://github.com/adobe/aio-lib-java/pull/202
> `aio-lib-osgi` added export instruction for auth package (#202)

- .gitignore
- pom.xml
By using the source and target version configuration of maven-compiler-plugin we have no way to control the usage of Java 11 specific API. The compilation will still work but the code will fail at runtime when the jar is used with Java 8. 
Until Java 8, the only way to cross compile was to use source and target versions but these configuration params do not check the compatibility of the API against the specified Java version. 
Starting with Java 9 we have a stricter configuration when we are cross compiling. Earlier we were using JDK 8 for compiling but since now we are using JDK 11 it is better to add this release tag to ensure Java 8 compatibility in the released jar.
Refer this link for more details: https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.h …
> GH-204 Setting the `--release` of the Java Compiler: to stick to Java `8` avoid accidental Java `11` api use

- .gitignore
- pom.xml
By using the source and target version configuration of maven-compiler-plugin we have no way to control the usage of Java 11 specific API. The compilation will still work but the code will fail at runtime when the jar is used with Java 8. 
Until Java 8, the only way to cross compile was to use source and target versions but these configuration params do not check the compatibility of the API against the specified Java version. 
Starting with Java 9 we have a stricter configuration when we are cross compiling. Earlier we were using JDK 8 for compiling but since now we are using JDK 11 it is better to add this release tag to ensure Java 8 compatibility in the released jar.
Refer this link for more details: https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.h …
> GH-204 Setting the `--release `of the Java Compiler: to stick to Java 8 and avoid accidental Java 11 api use

- events_mgmt/pom.xml
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/ConflictException.java
- events_mgmt/src/test/java/com/adobe/aio/event/management/feign/ConflictExceptionTest.java
`aio-lib-java-events-mgmt`:   adding missing `x-conflicting-id` header safe guard within `ConflictException`
#207 
added Unit test.
> GH-207 `aio-lib-java-events-mgmt`:   adding missing `x-conflicting-id` header safe guard within `ConflictException`

- ims/src/main/java/com/adobe/aio/ims/api/ImsApi.java
- ims/src/test/java/com/adobe/aio/ims/feign/FeignImsServiceTest.java
All operations which needs a token are failing when using OAuth based workspace
In the actual API call parameter-name is `scope` but sdk is using `scopes`
Sample Curl call
```
curl -X POST 'https://ims-na1-stg1.adobelogin.com/ims/token/v3' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&client_id=xxxxx&client_secret=xxxxxx&scope=yyyy,zzzzz'
```
I deployed the local build on AEM cloud and tested & the fix is working fine.
> GH-210: fixed scope parameter issue

- core/src/main/java/com/adobe/aio/util/feign/FeignUtil.java
Configure Retries in Feign utility:
- retry calls maximum 3 times (5 before)
- enlarge the maximum waiting period to 4s (1s before)
- use a larger base interval of 1s (100ms before)
#150 
This would better tune calls retries. We do not want in general to retry too much, and we want more time between each of the calls to wait for the called system to recover. Note that even in case of a retry after header present in the response, the maximum waiting period will be used in place of the time specified in the response to place the next call when lower: 
```java
if (e.retryAfter() != null) {
interval = e.retryAfter().getTime() - currentTimeMillis();
if (interval > maxPeriod) {
interval = maxPeriod;
}
```
which is ok to protect the service for hanging up for too long. 4s seems like a reasonable …
> GH-150: adjust feign retryer configuration

- events_test/src/main/java/com/adobe/aio/event/management/RegistrationServiceTester.java
- events_test/src/test/java/com/adobe/aio/event/management/ProviderServiceIntegrationTest.java
- ims/src/main/java/com/adobe/aio/util/WorkspaceUtil.java
See: #213 
As described in the issue, added the possibility to get the configuration for the `Workspace` from environment variables, which makes it easier to use.
Breaking change: renamed the method `WorkspaceUtil#getSystemWorkspaceBuilder` to `WorkspaceUtil#getWorkspaceBuilder`.
#213 
Enable the usage of environment variables in docker containers where an entrypoint is defined in exec form, passing the configurations through ENV variables without the need to bind them using the system properties, which turns out to be really cumbersome.
> GH-213: enhance WorkspaceUtil to also search in envrionment variables

- core/src/main/java/com/adobe/aio/util/feign/FeignUtil.java
- core/src/test/java/com/adobe/aio/util/feign/FeignUtilTest.java
Configure Retries in Feign utility:
- retry calls maximum 3 times (5 before)
- enlarge the maximum waiting period to 4s (1s before)
- use a larger base interval of 1s (100ms before)
#150 
https://github.com/adobe/aio-lib-java/pull/151
This would better tune calls retries. We do not want in general to retry too much, and we want more time between each of the calls to wait for the called system to recover. Note that even in case of a retry after header present in the response, the maximum waiting period will be used in place of the time specified in the response to place the next call when lower: 
```java
if (e.retryAfter() != null) {
interval = e.retryAfter().getTime() - currentTimeMillis();
if (interval > maxPeriod) {
interval = maxPeriod;
}
```
which is ok to protect the service for …
> GH-150: adjust feign retryer configuration (#151)

- .github/workflows/maven-release.yml
- .github/workflows/sitedocs.yaml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- core/src/main/java/com/adobe/aio/util/feign/FeignUtil.java
- events_ingress/src/main/java/com/adobe/aio/event/publish/PublishService.java
- events_ingress/src/main/java/com/adobe/aio/event/publish/api/PublishApi.java
- events_ingress/src/main/java/com/adobe/aio/event/publish/feign/FeignPublishService.java
- events_test/pom.xml
- events_test/src/main/java/com/adobe/aio/event/publish/PublishServiceTester.java
- events_test/src/test/java/com/adobe/aio/event/journal/JournalServiceIntegrationTest.java
- events_test/src/test/java/com/adobe/aio/event/publish/PublishServiceIntegrationTest.java
GH-221 wiring the new `x-event-phidata` header support in Adobe IO Events `eventsingress` `PublishApi`
> GH-221 wiring the new `x-event-phidata` header support in Adobe IO Events `eventsingress` `PublishApi`

- core/pom.xml
- core/src/main/java/com/adobe/aio/util/JacksonUtil.java
- pom.xml
GH-230
* removing unwanted/unneeded/unused cloudevent serializer and deserializer and hence dependency 
* It was introduced here https://github.com/adobe/aio-lib-java/pull/126 
* not sure why
* reminder: ISO Date formatting is coming for free in Jackson when using `@JsonFormat`
* we still have this https://github.com/adobe/aio-lib-java/issues/16 pending
* but for now I propose we remove this annoying dependency
> GH-230 removing unwanted/unneeded/unused cloudevent serializer and deserializer and hence dependency

- .github/workflows/maven-itest.yml
- events_mgmt/src/main/java/com/adobe/aio/event/management/RegistrationService.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/api/RegistrationApi.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/feign/FeignRegistrationService.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/CreateSubscriberFilterModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/CustomSampleEventModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/EventMetadataIdOutputModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/Registration.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/RegistrationCreateModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/RegistrationUpdateModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/SubscriberFilterModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/SubscriberFilterValidationInputModel.java
- events_mgmt/src/main/java/com/adobe/aio/event/management/model/SubscriberFilterValidationOutputModel.java
Through Subscriber Defined Filtering consumers will be able to add filters to their Registrations. The feature is still under development.
https://github.com/adobe/aio-lib-java/issues/233
> GH-233: add new Subscriber Filter API support

- pom.xml
GH-236 
As of June 30, 2025 Sonatype OSSRH has reached end of life and has been shut down. All OSSRH namespaces have been migrated to Central Publisher Portal.
Hence migrating to `central.sonatype.com`
> GH-236 migrating to `central.sonatype.com`

- .github/workflows/maven-release.yml
- .github/workflows/maven-snapshot.yml
- pom.xml
GH-236 
As of June 30, 2025 Sonatype OSSRH has reached end of life and has been shut down. All OSSRH namespaces have been migrated to Central Publisher Portal.
Hence migrating to `central.sonatype.com` see https://github.com/adobe/aio-lib-java/pull/237
and now with this aligning the GH actions with the above change
> GH-236 aligning the GH action to the use of `central-publishing-maven-plugin` plugin
